apiVersion: apps/v1
kind: Deployment
metadata:
  name: appnode
  labels:
    app: appnode
spec:
  replicas: 5
  selector:
    matchLabels:
      app: appnode
  template:
    metadata:
      labels:
        app: appnode
    spec:
      containers:
      - name: appnode
        image: acrx05042024.azurecr.io/appnode
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: appnode
spec:
  selector:
    app: appnode
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer